### ISSUE TITLE
2.2.1以后版本无法导入文件

### ISSUE THREAD

**Issue by stsiao** [acely/Arctime-Pro#16]
> Archlinux
>KDE环境
> openjdk 1.8.0

2.2.1以后的版本，拖入文件抛异常
 ```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.arctime.main.ArcTime.a(Unknown Source)
        at org.arctime.main.ArcTime.a(Unknown Source)
        at P.ir.drop(Unknown Source)
        at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
        at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
        at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:184)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
        at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
        at java.awt.Component.dispatchEventImpl(Component.java:4744)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

通过菜单的导入按钮有同样的异常。

2.2.1版本无此问题

**Comment by acely** [comment]
此问题已修复，请测试2.4.1的Beta包，欢迎后续反馈
[http://dl.arctime.cn/b/ARCTIME_PRO_2.4.1_LINUX_Beta4.7z](url)
