### ISSUE TITLE
Crash on Linux when execute run.sh 

### ISSUE THREAD

**Issue by svenjung** [acely/Arctime-Pro#7]
ubuntu 14.04 LTS

# sh run.sh 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bulenkov.iconloader.IconLoader.<clinit>(IconLoader.java:53)
	at com.bulenkov.darcula.DarculaLaf.getDefaults(DarculaLaf.java:101)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at org.arctime.main.ArcTime.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 4 more

**Comment by ThinkerQAQ** [comment]
Same problem...

**Comment by acely** [comment]
@ThinkerQAQ Which version do you use?

**Comment by ThinkerQAQ** [comment]
OS: ArchLinux, kernel version is 4.16.13-2
Java: open-jdk8
vlc: 3.0.3-1
arctime:1.2

**Comment by acely** [comment]
@ThinkerQAQ OK...
1. This repository is for Arctime Pro, 1.2 is standard version.
2. Pro version contains all features of standard version. And those features remains free.
3. So pls use latest version of Arctime  Pro.
4. If still encounters that error, replace "iconloader-20170615.jar" (in ArcTime_lib folder) with this file.
[iconloader.jar.zip](https://github.com/acely/Arctime-Pro/files/2096362/iconloader.jar.zip)

**Comment by ThinkerQAQ** [comment]
After replace this lib, it works well. Thank you!

**Comment by ghost** [comment]
Ubuntu can not run run.sh
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bulenkov.darcula.DarculaLaf (file:/home/daidai/Downloads/ARCTIMEpro221/ArcTime_lib/darcula.jar) to field javax.swing.text.html.HTMLEditorKit.DEFAULT_STYLES_KEY
WARNING: Please consider reporting this to the maintainers of com.bulenkov.darcula.DarculaLaf
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities$Translucency
	at org.arctime.main.ArcTime.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities$Translucency
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

**Comment by acely** [comment]
@ghost should use jre 8
